name: flutter_mentor
description: Flutter mentoring project

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  firebase_core: ^0.3.4
  firebase_analytics: ^2.1.1+3
  cloud_firestore: ^0.10.1
  firebase_auth: ^0.8.4+5
  google_sign_in: ^4.0.1+1
  fancy_on_boarding: ^1.2.0
  http: '0.11.3+17'
  rxdart: '0.21.0'
  shared_preferences: '0.5.3'

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

    - family: SourceSansPro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf

  uses-material-design: true

  assets:
    - assets/images/login_background.jpg
    - assets/images/student.png
    - assets/images/teacher.png
    - assets/images/path.png


