name: flutter_mentor
description: Flutter mentoring project

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  
  flutter_localizations:
    sdk: flutter

  http: '0.11.3+17'
  rxdart: '0.21.0'
  shared_preferences: '0.4.2'


dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
   - assets/images/avatar.png
   - assets/images/flag-fr.png
   - assets/images/flag-en.png
   - assets/images/flag-de.png
   - assets/images/flag-es.png
   - assets/images/flag-it.png
   - assets/images/flag-nl.png
   - assets/images/flag-pt.png
   - assets/locales/locale_fr.json
   - assets/locales/locale_en.json
